### ISSUE TITLE
MAPA MENTAL DE CONJUNTOS Y RELACIONES

### ISSUE THREAD

**Issue by yanet02** [SistemasTecTlaxiaco/mapa-mental-yanet-02#2]
[MAPA MENTAL-CONJUNTOS-RELACIONES-YANET GONZÁLEZZ GARCÍA.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-yanet-02/files/7272738/MAPA.MENTAL-CONJUNTOS-RELACIONES-YANET.GONZALEZZ.GARCIA.pdf)

**Comment by alexis663** [comment]
manejo conceptual y dominio conceptual del tema (excelente) identifico mínimo 8 elementos de un sistema multimedia 25 puntos
relación entre conceptos incluidos en el mapa (excelente) los conceptos son claros y coherentes 25 puntos 
calidad de presentación (excelente) uso colores y aporta información adicional 25 puntos
jerarquía (excelente) conceptos jerarquizados en forma lógica excelente orden 25 puntos
total:100/100
calificacion:20%/20%
calificado por: Alexis Juarez Hernández

**Comment by josealfredo79** [comment]
Bien hecho y revisado
